export const SET_NOTE = 'SET_NOTE'
export const ADD_NOTE = 'ADD_NOTE'
export const DEL_NOTE = 'DEL_NOTE'
export const SET_TOTAL = 'SET_TOTAL'
export const SET_TITLE = 'SET_TITLE'
export const SET_NOTE_ACTIVE = 'SET_NOTE_ACTIVE'

export const SET_LIST = 'SET_LIST'
export const SET_LIST_ACTIVE = 'SET_LIST_ACTIVE'
export const SET_LIST_TITLE = 'SET_LIST_TITLE'
export const SET_LIST_MAIN = 'SET_LIST_MAIN'
export const EMPTY_LIST = 'EMPTY_LIST'
export const ADD_LIST = 'ADD_LIST'
export const DEL_LIST = 'DEL_LIST'
